# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/nice_icon.png

# Theme Main Subtitle
subtitle_main: nice前端团队

# Theme Secondary subtitle
susbtitle_secondary: 在nice，你可以尽情记录和分享你的生活，结识跟你有共同兴趣爱好和生活方式的朋友。

# Footer About Section
about_footer: 致力于打造一个属于年轻人的自由分享社区。

# Default post title
default_post_title: Hello World

# Default post cover index page (Recommended)
default_cover_index: "http://o8sxkcont.bkt.clouddn.com/nature.jpeg"

# Default post cover index page (Optional)
default_cover_detail: ""

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
facebook_url:
instagram_url:
dribble_url:
github_url: https://github.com/nicefe
behance_url:
fivehundredpx_url:
email_url: \#
rss_url: \#
